### ISSUE TITLE
React Object table is slow when dealing with 400+ rows with 12 columns

### ISSUE THREAD

**Issue by alpha1d3d** [ABASystems/react-object-table#7]
Created a PR to fix it: https://github.com/ABASystems/react-object-table/pull/6

However assumes that background is white and sets overlay to white. Let me know if there is a better way.

**Comment by bor3ham** [comment]
Fixed with 1.0.1

Still not _super_ snappy for massive data sets as there is a lot of logic that gets replayed in the `ApiTable` render method, but much better than before

**Comment by nickmellor** [comment]
Hi Michael,

Fixed with 1.0.1-- unpack this for me? :)

Cheers,

Nick

**Comment by bor3ham** [comment]
Hey Nick,

I've made my own patch that addresses the issue on master, and shipped a release on `npm` as version `1.0.1`. The only changes required were:
https://github.com/ABASystems/react-object-table/commit/1b3f123ff2d6c1b83b53ae91c70105fd53b0efdd

For our usage on `abas-web` I made some similar optimisations to the `ApiTable` component, which have been pushed to `develop`

**Comment by nickmellor** [comment]
Thanks heaps!
